apiVersion: apps/v1
kind: Deployment
metadata:
 name: the-deployment
 labels:
   deployment: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment: demo
    spec:
      containers:
      - name: hello
        image: registry.fpl.expert/humanbe88/hellonode:13
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
        env:
        - name: MY_MYSQL_DB
          valueFrom:
            configMapKeyRef:
              name: the-map
              key: mysqlDB
      imagePullSecrets:
      - name: regcred
